inherit_from: .rubocop_todo.yml

# we still support ruby 1.8
Style/HashSyntax:
  Enabled: false

#Metric cops are rarely useful
Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
    - ./*.gemspec

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ModuleLength:
  Max: 185

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/AccessModifierDeclarations:
  Enabled: false
