name: Test

on:
  pull_request: {}
  push:
    branches:
      - master

env:
  BUNDLE_WITHOUT: release

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true
      - name: Run Rubocop
        run: bundle exec rake rubocop
  rspec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"
          - "3.3"
    env:
      # https://github.com/rubygems/rubygems/issues/5234#issuecomment-1003773622
      RUBYOPT: '--disable-did_you_mean'
    name: RSpec - Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: spec tests
        run: bundle exec rake test
      - name: Verify gem builds
        run: gem build --strict --verbose *.gemspec

  tests:
    needs:
      - rubocop
      - rspec
    runs-on: ubuntu-latest
    name: Test suite
    steps:
      - run: echo Test suite completed
